spring.application.name=cine-api

spring.datasource.url=jdbc:postgresql://localhost:5432/cine_iii
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
